site_name: JGNN
site_author: Emmanouil Krasanakis
# repo_url: https://github.com/MKLab-ITI/JGNN
copyright: Copyright &copy; 2024 Emmanouil Krasanakis

nav:
  - Home: 'index.md'
  - Setup: 'setup.md'
  - Quickstart: 'quickstart.md'
  - Tutorial:
      - 'tutorial/models.md'
      - 'tutorial/builders.md'
      - 'tutorial/neuralang.md'
      - 'tutorial/training.md'
  - Topics:
      - 'topics/advanced.md'
      - 'topics/invariant.md'
      - 'topics/debugging.md'

markdown_extensions:
  - admonition
  - mkautodoc
  - attr_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      pygments_style: friendly
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.gemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

theme:
  name: mkdocs
  logo: logo.ico  # Path to your logo file
  favicon: logo.ico  # Path to your favicon file
  color_mode: auto
  user_color_mode_toggle: True
  nav_style: dark

  features:
    - search.suggest
    - navigation.scroll

extra_css:
  - theme_extend.css  # Custom CSS file for additional styling

extra_javascript:
  - mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocstrings

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MKLab-ITI/JGNN
      name: Emmanouil Krasanakis
